HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <head><title>Servicio No Disponible</title></head>
  <body>
    <h1>Disculpe, el servicio no se encuentra disponible</h1>
    <p>Por favor, intente más tarde.</p>
  </body>
</html>